# Generated by Django 4.1.1 on 2022-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_alter_contract_company_reg_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="annualised_budget",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="commission_per_annum",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="commission_per_unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="company_reg_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="day_consumption",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="eac",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contract",
            name="meter_serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="night_consumption",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="partner_commission",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="profile",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="standard_charge_monthly",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="top_line",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="annualised_budget",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="commission_per_annum",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="commission_per_unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="company_reg_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="day_consumption",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="eac",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="meter_serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="night_consumption",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="partner_commission",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="profile",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="standard_charge_monthly",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="top_line",
            field=models.CharField(max_length=40),
        ),
    ]
