# Generated by Django 4.1.1 on 2022-09-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="collector_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="property_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="collector_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="property_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
